export const BEGIN_FETCH = "BEGIN_FETCH";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const USER_SIGNED_IN = "USER_SIGNED_IN";
export const USER_SIGNED_OUT = "USER_SIGNED_OUT";

export const GLOBAL_BEGAN_FETCH = "GLOBAL_BEGAN_FETCH";
export const GLOBAL_SUCCESS = "GLOBAL_SUCCESS";
export const GLOBAL_ERROR = "GLOBAL_ERROR";

export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEM_CATEGORIES_SUCCESS = "FETCH_ITEM_CATEGORIES_SUCCESS";
export const FETCH_ITEM_LOCATIONS_SUCCESS = "FETCH_ITEM_LOCATIONS_SUCCESS";
export const FETCH_ITEM_AMOUNTS_SUCCESS = "FETCH_ITEM_AMOUNTS_SUCCESS";

export const FETCH_PANTRIES_SUCCESS = "FETCH_PANTRIES_SUCCESS";
